nombre = input("Introduce tu nombre: ")
apellidos = input("Introduce tus apellidos: ")
edad = int(input("Introduce tu edad: "))
carrera = input("Introduce tu carrera: ")
expediente = int(input("Introduce tu expediente: "))
ciudad_de_origen = input("Introduce tu ciudad de origen: ")
foraneo = input("Introduce si eres foraneo ( Y, N ): ")
codigo_postal = int(input("Introduce tu codigo postal: "))
altura = int(input("Introduce tu altura: "))
peso = int(input("Introduce tu peso: "))

print("Nombre: ", nombre, apellidos)
print("Carrera: ", carrera, end=", ")
print("Expediente: ", expediente)
print("Ciudad de origen: ", ciudad_de_origen)
print("Altura: ",altura, end="mts, ")
print("Peso: ", peso, end="kgs")